### ISSUE TITLE
Zoom REST API code error: 1009

### ISSUE THREAD

**Issue by sanjosedennis7593** [zoom/api#7] opened 2017-08-03 07:39 UTC
Hi,

I have tried to create an account using the zoom rest api cust create account, however i can't register an email account.

It return a response something like this.

{"error":{"code":1009,"message":"The user myemail@gmail.com already holds an active account."}}

What does this mean?

Thanks.

**Comment by joshuawoodward** [comment] 2017-08-07 16:19
It means that email address is already associated with another Zoom account and is marked as active.

**Closed by joshuawoodward** 2017-08-07 16:19 UTC

**Comment by sanjosedennis7593** [comment] 2017-08-07 18:34
Is there any other solution for this issue so that i can register a specified email under my account?

**Comment by joshuawoodward** [comment] 2017-08-07 18:54
No, this is by design, otherwise you could register every user from Company X to your account and remove them from their previous account.

The account admin from the previous would have to go in and remove this user(s)
